### ISSUE TITLE
Community Bounty #21 - "Website Translation" 

### ISSUE THREAD

**Issue by bwhm** [Joystream/community-repo#212]
### Tags
- `Coding`
- `Research`

### Description
Translate the joystream.org website to languages other than English.

#### Reward
USD 500 per "top" language.
- Russian, Spanish, French, Mandarin

USD 300 for other languages pending approval from Jsgenesis.
- For example, translating to Norwegian would not warrant a reward, as it's both a language few speaks, and almost every Norwegian are proficient in English.

#### Success Events
1. Translate the entire page in to one of the "approved" languages.
  - This must be done by copying and editing the `*.json` as described in [Resources](#resources).
  - Make sure you are consistent, and choose the same words and phrases whenever applicable.
2. Test deploy your translation, and review how your translation "looks".
  - It must be assumed that the translated content will not have the exact same amount of characters as the English original. If the number of characters in a headline/sentence/section strays "too" far away from the original, it may look bad and perhaps also break the responsiveness.
  - In some cases, this can be fixed by choosing other words and phrases without losing anything of meaning, but in other cases, this will not be possible.
  - Once you've completed the first draft of the first page, it is advisable:
    - build and test deploy
    - look at the page(s) and compare it to the "look" and responsiveness to the original
    - make a note of everything that is off
    - consider alternatives **if**, and **only if**, it won't degrade the message
    - if not, make a note of the exact line (in the json) that causes issues, so that you can include this in your PR.
      - then, we can make the changes required and keep both context and "look"

#### Resources
A step by step guide for how to:
- get started
- translate parts and review your work
- manage branches and workflow
can be found [here](https://github.com/Joystream/joystream-org/tree/master/src/locales/CONTRIBUTING.md).

#### Conditions
- All PRs must be made to the [translation](https://github.com/Joystream/joystream-org/tree/translation) branch. Jsgenesis will make the PRs to `development` and master.
- The entire site must translated before any parts of the Bounty is paid out, even if "your" part is completed and accepted.
- If there are any changes made to the master branch before the Bounty is completed, those new pages/sections must be translated.

#### Annihilation
**The below applies to the Bounty Manager/Council only, and is not necessarily relevant for the entrants.**

#### Format
Jsgenesis proposes a ["Closed"](https://github.com/Joystream/helpdesk/tree/master/roles/council-members#closed-format) format.

If there are multiple strong applicants presenting themselves, the BM could choose to have them either co-operate, or instead have them "compete" for the best translation of a specific page.

Individual BMs should be assigned to each of the languages, where the BM should be at least proficient in said language.

#### Review Period
Jsgenesis may take 10 days after the PR with the complete translation, for all pages, have been included in a PR to the Community Repo, with an approved spending proposal.

#### Status
Open.

**Comment by bwhm** [comment]
@mochet @DzhideX

**Comment by OIgnat** [comment]
Comments regarding Russian translation pull request:

Discord user name: AlexZNet#0968 (for any feedbacks or requests for fixes depending on below points or any other reasons).

1. Some terms, like 'Blockchain developer' that contain well-known definitions are translated leaving those definitions as they are. For example 'Blockchain разработчик'. It is usually called in this way locally and will not make any confusion, but looks familiar to everyone. However, if fully native translation looks better, this could be changed.
1.1. at the same time, 'blockchain' and similar definitions were translated.
1.2. definitions like 'testnet' are used as transliterations, because they are commonly used in community and could be understand better than translating them as 'test network' value. Also, definition is simple enough to be understand even for those who do not know, what 'testnet' is.

2. Unlike English, in Russian there are a couple of ways of addressing people, who read text. Let's imagine, as example 'You' and 'you' (can't be expressed as simple, though) - the last one is more modern and simple approach, that, to my mind, fit Joystream concept, according to what I have read at different pages like branding or about Joustream. But if you think the 1-st, more formal one, is better - I can change that.

3. There are some blocks of text like 'day' and 'days'. In Russian there multiple possible values for multiples - but applying this would need technical improvements on website. So multiples were used in the most common use cases.

4. The names of testnets are left in Latin - because they are original names. At the same time, when used in the meaning of city (like Rome as a city) - they were translated.

5. After setting up website locally and checking how it looks like after translation I noticed that 'Road to mainnet' on landing page is not changed, even being translated in json file. So looks like a hardcoded value.

6. At brand page there are definitions like 'Joysteram Blue' & Gray. As I get, those are namings, so they were left as definitions.

**Comment by OIgnat** [comment]
Added Ukrainian translation to same pull request.

**Comment by maxlevush** [comment]
Opened https://testnet.joystream.org/#/forum/threads/493

**Comment by zubastik096** [comment]
Hey! I can translate into 2 languages: Russian and Ukrainian.

**Comment by freakstatic** [comment]
> Hey! I can translate into 2 languages: Russian and Ukrainian.

Hi! 
left a reply here:
https://testnet.joystream.org/#/forum/threads/493?replyIdx=10

**Comment by StrowDeATh** [comment]
Hey! I can translate it into Spanish.

**Comment by mochet** [comment]
This bounty is no longer relevant to the new system, closing this to avoid confusion
