### ISSUE TITLE
governance: Standard Operating Procedure - Template

### ISSUE THREAD

**Issue by mrexpat** [Joystream/community-repo#498]
## Purpose
Standard Operating Procedures are routine tasks that are done by an organization, using the same process every time. This creates the need for documentation of the process so that anyone can pick it up and execute it the same way as it was done in the past.

To create your own SOP, use this template, including this section, where you describe the background / need for the SOP.

## Scope
Identify the intended audience and / or activities where the SOP may be relevant

## Prerequisites
Outline information required before proceeding with the listed procedure, for example, worksheets, documents, reports, etc.

## Responsibilities
Identify the personnel that have a primary role in the sSOP and describe how their responsibilities relate to this SOP. If necessary, include contact information.

## Procedure
Provide the steps required to perform this procedure (who, what, when where, why, how). Include a process flow chart.

## References
List resources that may be useful when performing the procedure, for example Admin policies, Municipal code, government standards, and other SOP's.

## Definitions
Identify and define frequently used terms or acronyms. Provide additional and/or relevant information needed to understand this SOP.

**Comment by robertneckelius** [comment]
`## Purpose
Standard Operating Procedures are routine tasks that are done by an organization, using the same process every time. This creates the need for documentation of the process so that anyone can pick it up and execute it the same way as it was done in the past.

To create your own SOP, use this template, including this section, where you describe the background / need for the SOP.

## Scope
Identify the intended audience and / or activities where the SOP may be relevant

## Prerequisites
Outline information required before proceeding with the listed procedure, for example, worksheets, documents, reports, etc.

## Responsibilities
Identify the personnel that have a primary role in the sSOP and describe how their responsibilities relate to this SOP. If necessary, include contact information.

## Procedure
Provide the steps required to perform this procedure (who, what, when where, why, how). Include a process flow chart.

## References
List resources that may be useful when performing the procedure, for example Admin policies, Municipal code, government standards, and other SOP's.

## Definitions
Identify and define frequently used terms or acronyms. Provide additional and/or relevant information needed to understand this SOP.`

**Comment by mochet** [comment]
@mrexpat I hope you don't mind, I edited the title and have included this as part of a Governance initiative since it seems relevant to have: https://github.com/Joystream/community-repo/issues/710
