### ISSUE TITLE
Fix Working Groups bot

### ISSUE THREAD

**Issue by singulart** [Joystream/community-repo#754]
Olympia release came with a lot of breaking changes, which resulted in the majority of the community tools being broken, too. This includes a Working Groups discord bot: https://github.com/Joystream/community-repo/tree/master/scripts/wg-bot which proved to be extremely useful in Sumer and Giza networks.

This ticket is about Working Groups bot and includes the following things to be done:
1) Make the bot work with Olympia events
2) Provide / fix tests for all supported events
3) Deploy the bot code to Heroku
4) Isolate the code in the standalone repo suitable for Heroku
5) Validate that the functionality is working in Joystream Operations server.

Estimate: `15-20h`, mainly due to significant API changes. 
Story Points: `8`
Priority: `Blocker`

**Comment by singulart** [comment]
Approved proposal: https://dao.joystream.org/#/proposals/preview/105

**Comment by singulart** [comment]
Due to clumsiness of [community monorepo](https://github.com/Joystream/community-repo) (used to store literally each and every community tool!), and to streamline Heroku deployments, I've decided to create a [separate repo](https://github.com/singulart/joy-disco-bots) specifically for Joystream bots.

**Comment by singulart** [comment]
@freakstatic @oleksanderkorn Please conduct the internal code review. I must add that there isn't a PR, so code has to be reviewed right in the repo. Use comments to provide feedback. Thank you!

**Comment by freakstatic** [comment]
> @freakstatic @oleksanderkorn Please conduct the internal code review. I must add that there isn't a PR, so code has to be reviewed right in the repo. Use comments to provide feedback. Thank you!

First of all good choice to merge all the bots in one, looks good! 
But I have a suggestion to make:

can't be use a async sleep here?
https://github.com/singulart/joy-disco-bots/blob/b11f29f84c89192c57e0a84bdf150db49e7e6f12/src/wg/wg_event_handlers.ts#L144

blocking the event loop doesn't seem a good choice, it could be used something like this

```
function delay(ms: number) {
    return new Promise( resolve => setTimeout(resolve, ms) );
}
```
`await delay(6000);`

**Comment by singulart** [comment]
@DzhideX Please have a look at this code: https://github.com/singulart/joy-disco-bots and leave a comment if you notice something substantially wrong. This code isn't going to be merged to community repo anyway, so JSG review is rather a formality..

**Comment by bwhm** [comment]
@singulart 

> This code isn't going to be merged to community repo anyway, so JSG review is rather a formality..

Not sure I understand what you mean here?
If something is going to count towards the builders score, I don't think it's just a formality.

**Comment by singulart** [comment]
> @singulart
> 
> > This code isn't going to be merged to community repo anyway, so JSG review is rather a formality..
> 
> Not sure I understand what you mean here? If something is going to count towards the builders score, I don't think it's just a formality.

Point taken. As there isn't any pull request here, not sure how JSG will comment their findings, if any.  @DzhideX Thoughts?

**Comment by DzhideX** [comment]
I don't see why I shouldn't just leave my review/thoughts here so that is what I will do (but I'll ping @bwhm just in case) .

So, in terms of the functionality, the code looks fine to me and judging by that alone I can **_approve_** this work! There is some stuff I'd like to add to that though:

- The `wg-bot` inside of the community-repo itself seems to be of an older version, I assume we want to update that to this new updated work (probably after it's been approved but just to check!)
- Wrt the code itself, everything was fine for the most part but I'd just like to ask you to maybe split up the code a bit and try to avoid that much nesting as it can get quite difficult to parse (ref: [this](https://github.com/singulart/joy-disco-bots/blob/master/src/wg/wg_event_handlers.ts)) (this isn't a blocking comment though, just something to keep in mind for future work)

Great work! And as is customary I'll end with a: LGTM! (✅ **_Approved_**)

**Comment by singulart** [comment]
Appreciate the prompt response @DzhideX! The `wg-bot` is indeed an older version, and in fact I am striving to unify all the similar functionalities (Working Groups, Forum, Atlas videos, etc) in one modular architecture. In the next version I'll introduce the basic building blocks of this new architecture.
